# Random forest

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
## load the iris dataset

from sklearn.datasets import load_iris
iris=load_iris()

In [3]:
# store the feature matrix (X) and response vector (y)
X = iris.data   
y = iris.target

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [6]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 100,random_state=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(random_state=10)

In [49]:
#predicting the values
RF_pred=classifier.predict(x_test)

In [50]:
RF_pred

array([1, 1, 0, 0, 2, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 0, 0, 2,
       2, 2, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 1, 1, 1, 2,
       2])

In [51]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,RF_pred)
acc

0.9777777777777777

In [52]:
#making prediction on new data 

classifier.predict([[3, 5, 4, 2]])

array([1])

In [53]:
species_idx = classifier.predict([[3, 5, 4, 2]])[0]
iris.target_names[species_idx]

'versicolor'

In [54]:
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [55]:
rf_param_grid = {'max_samples': [0.1, 0.2, 0.3, 0.4],
                'max_features': [1, 2],
                'n_estimators':[10, 50, 100],
                'max_depth': [8, 9, 10]
                }
rf_cv = KFold(n_splits=5)
rf_grid = GridSearchCV(RandomForestClassifier(), rf_param_grid, cv=rf_cv)
rf_grid.fit(x_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=RandomForestClassifier(),
             param_grid={'max_depth': [8, 9, 10], 'max_features': [1, 2],
                         'max_samples': [0.1, 0.2, 0.3, 0.4],
                         'n_estimators': [10, 50, 100]})

In [56]:
print('RF best Parameters:', rf_grid.best_estimator_)
print('RF best Score:', rf_grid.best_score_)

RF best Parameters: RandomForestClassifier(max_depth=8, max_features=2, max_samples=0.4)
RF best Score: 0.961904761904762


# Adaboost

In [8]:
from sklearn.ensemble import AdaBoostClassifier
adclf=AdaBoostClassifier(n_estimators=100,learning_rate=1,random_state=40)
adclf.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=1, n_estimators=100, random_state=40)

In [58]:
AB_pred=adclf.predict(x_test)

In [59]:
AB_pred

array([1, 1, 0, 0, 2, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 0, 0, 2,
       2, 2, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 1, 1, 1, 2,
       2])

In [60]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,AB_pred)
acc*100

97.77777777777777

In [63]:
ab_grid_param = {'learning_rate': [0.01, 0.05, 0.1, 1],
                 'n_estimators' : [10, 50, 100],
                 }
ab_cv = KFold(n_splits=5)
ab_grid = GridSearchCV(AdaBoostClassifier(), ab_grid_param, cv=ab_cv)
ab_grid.fit(x_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.01, 0.05, 0.1, 1],
                         'n_estimators': [10, 50, 100]})

In [64]:
print('AB best Parameters:', ab_grid.best_estimator_)
print('AB best Score:', ab_grid.best_score_)

AB best Parameters: AdaBoostClassifier(learning_rate=1, n_estimators=100)
AB best Score: 0.9333333333333332


In [62]:
#AdaBoostClassifier?

# Gradient boosting

In [65]:
from sklearn.ensemble import GradientBoostingClassifier
Gb_CLF=GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,random_state=10)
Gb_CLF.fit(x_train,y_train)

GradientBoostingClassifier(random_state=10)

In [66]:
Gb_pred=Gb_CLF.predict(x_test)
Gb_pred

array([1, 1, 0, 0, 2, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 0, 0, 2,
       2, 2, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 1, 1, 1, 2,
       2])

In [67]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,Gb_pred)
print("Accuracy score \n" ,acc*100)

print("\nconfusion matrix\n",confusion_matrix(y_test,Gb_pred))

print("\nClassification report\n",classification_report(y_test,Gb_pred))

Accuracy score 
 97.77777777777777

confusion matrix
 [[14  0  0]
 [ 0 15  0]
 [ 0  1 15]]

Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [68]:
gb_grid_param = {'learning_rate': [0.01, 0.05, 0.1, 1],
                 'n_estimators' : [10, 50, 100],
                 'max_depth': [2, 5, 8, 11],
                 'max_features': [1,2]}
gb_cv = KFold(n_splits=5)
gb_grid = GridSearchCV(GradientBoostingClassifier(), gb_grid_param, cv=gb_cv)
gb_grid.fit(x_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.05, 0.1, 1],
                         'max_depth': [2, 5, 8, 11], 'max_features': [1, 2],
                         'n_estimators': [10, 50, 100]})

In [69]:
print('GB best Parameters:', gb_grid.best_estimator_)
print('GB best Score:', gb_grid.best_score_)

GB best Parameters: GradientBoostingClassifier(learning_rate=0.05, max_depth=2, max_features=1)
GB best Score: 0.9523809523809523


In [72]:
gb_y_pred = gb_grid.predict(x_test)
print('\nAccuray:\n', accuracy_score(y_test, gb_y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, gb_y_pred))
print('\nClassification Report:\n', classification_report(y_test, gb_y_pred))



Accuray:
 0.9777777777777777

Confusion Matrix:
 [[14  0  0]
 [ 0 15  0]
 [ 0  1 15]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



# xgboost

In [74]:
#pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [75]:
import xgboost as xgb 

In [76]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [77]:
xg_clf=xgb.XGBClassifier()
xg_clf.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [78]:
xg_pred=xg_clf.predict(x_test)

In [79]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,xg_pred)
acc

0.9777777777777777

In [80]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,xg_pred)
print("Accuracy score \n" ,acc*100)

print("\nconfusion matrix\n",confusion_matrix(y_test,xg_pred))

print("\nClassification report\n",classification_report(y_test,xg_pred))

Accuracy score 
 97.77777777777777

confusion matrix
 [[14  0  0]
 [ 0 15  0]
 [ 0  1 15]]

Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

